clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: oe_bootstrap_theme

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - DOCUMENT_ROOT=/test/oe_bootstrap_theme

pipeline:
  npm-build:
    group: prepare
    image: registry.fpfis.eu/fpfis/node:14
    commands:
      - npm install --unsafe-perm
      - NODE_ENV=production npm run production

  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  before-release:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/run release:create-archive --tag=${DRONE_TAG}
    when:
      event: tag

  github-release:
    image: registry.fpfis.eu/drone-plugins/github-release
    secrets: [ github_token ]
    files: oe_bootstrap_theme-${DRONE_TAG}.tar.gz
    when:
      event: tag
      matrix:
        COMPOSER_BOUNDARY: highest

matrix:
  COMPOSER_BOUNDARY:
    - highest
  PHP_VERSION:
    - 7.1
