<?php

/**
 * @file
 * The OpenEuropa Content Featured media field module.
 */

declare(strict_types = 1);

/**
 * Implements hook_preprocess_HOOK().
 */
function oe_bootstrap_theme_featured_media_field_preprocess_pattern_content_banner(&$variables) {
  // Set the image at the root, as waited in pattern template.
  _oe_bootstrap_theme_featured_media_field__set_image_object($variables);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function oe_bootstrap_theme_featured_media_field_preprocess_pattern_card(&$variables) {
  // Set the image at the root, as waited in pattern template.
  _oe_bootstrap_theme_featured_media_field__set_image_object($variables);
}


/**
 * Implements hook_aggregator_fetcher_info_alter().
 */
function _oe_bootstrap_theme_featured_media_field__set_image_object(&$variables) {
  if(!empty($variables['image']['oe_featured_media'][0]['#image']['src'])) {
    $variables['image'] = $variables['image']['oe_featured_media'][0]['#image'];
  }
}
