name: 'Media remote video copyright'
description: 'Adds a reusable copyright text field to remotely hosted videos and exposes it in the default view mode.'
type: 'Field'
recipes:
  - core/recipes/remote_video_media_type
install:
  - media
config:
  strict: false
  actions:
    core.entity_view_display.media.remote_video.default:
      simpleConfigUpdate:
        content.media_copyright:
          type: string
          label: visually_hidden
          settings:
            link_to_entity: false
          third_party_settings: { }
          weight: 1
          region: content
        hidden.media_copyright: false
    core.entity_form_display.media.remote_video.default:
      simpleConfigUpdate:
        content.media_copyright:
          type: string_textfield
          settings:
            size: 60
            placeholder: ''
          third_party_settings: { }
          weight: 1
          region: content
        hidden.media_copyright: false
