name: 'Media AV Portal photo copyright'
description: 'Adds a reusable copyright text field to AV Portal photos and exposes it in the default view mode.'
type: 'Field'
install:
  - media
config:
  strict: false
  actions:
    core.entity_view_display.media.av_portal_photo.default:
      simpleConfigUpdate:
        content.field_media_copyright:
          type: string
          label: visually_hidden
          settings:
            link_to_entity: false
          third_party_settings: { }
          weight: 1
          region: content
        hidden.field_media_copyright: false
    core.entity_form_display.media.av_portal_photo.default:
      simpleConfigUpdate:
        content.field_media_copyright:
          type: string_textfield
          settings:
            size: 60
            placeholder: ''
          third_party_settings: { }
          weight: 1
          region: content
        hidden.field_media_copyright: false
